# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerHub_connection: 'manual_kubernetes_connection1'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: 'Deploy to Docker Hub'
      inputs:
        containerRegistry: $(dockerHub_connection)
        repository: '4pwn/nginx_sample'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    
    - task: KubernetesManifest@0
      displayName: 'Create kubernetes Secret'
      inputs:
        action: 'createSecret'
        kubernetesServiceConnection: $(dockerHub_connection)
        namespace: 'dev'
        secretType: 'dockerRegistry'
        secretName: 'demo-secret'
        dockerRegistryEndpoint: $(dockerHub_connection)


    - task: KubernetesManifest@0
      displayName: 'Deploy to kubernetes'
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: $(dockerHub_connection)
        namespace: 'dev'
        manifests: |
                  $(Build.SourcesDirectory)/manifests_main/deployment.yml
                  $(Build.SourcesDirectory)/manifests_main/service.yml
        containers: '4pwn/nginx_sample:$(Build.BuildId)'
        imagePullSecrets: 'demo-secret'
